import { ArrowRight, CalendarDays, CheckCircle2, Leaf, PackageCheck, Sparkles } from 'lucide-react';
import StatCard from '../components/StatCard';

export default function Dashboard({ data, navigate }) {
  const lowStock = data.inventory.filter((item) => item.quantity <= item.minimum_threshold);
  const completed = data.tasks.filter((task) => task.is_completed).length;
  const next = data.menu[0];
  return <div className="page-content dashboard-page">
    <section className="hero-panel soft-outset"><div><p className="eyebrow">Tuesday, 25 August 2026</p><h2>Make space for<br /><em>good food.</em></h2><p className="hero-copy">Your calm command center for planning the week, keeping the pantry fresh, and turning good intentions into dinner.</p><button className="primary-button" onClick={() => navigate('menu')}>Open this week's menu <ArrowRight size={16} /></button></div><div className="hero-orbit"><div className="orbit-ring" /><div className="hero-bowl">🥗</div><span className="orbit-tag tag-one">Fresh & balanced</span><span className="orbit-tag tag-two">5 days planned</span></div></section>
    <div className="section-heading"><div><p className="eyebrow">At a glance</p><h3>Your kitchen today</h3></div><button className="text-button" onClick={() => navigate('pantry')}>View pantry <ArrowRight size={15} /></button></div>
    <section className="stats-grid"><StatCard label="Menu planned" value={`${data.menu.length} meals`} detail="Monday to Friday" tone="green" icon={CalendarDays} /><StatCard label="Pantry items" value={data.inventory.length} detail={`${lowStock.length} need attention`} tone="coral" icon={Leaf} /><StatCard label="Prep progress" value={`${completed}/${data.tasks.length}`} detail="tasks complete" tone="yellow" icon={CheckCircle2} /><StatCard label="Stock health" value={lowStock.length ? 'Review' : 'Great'} detail="Based on thresholds" tone="blue" icon={PackageCheck} /></section>
    <section className="dashboard-grid"><article className="content-card soft-outset"><div className="card-heading"><div><p className="eyebrow">Next on the table</p><h3>{next?.dish_name || 'No meal planned'}</h3></div><span className="day-chip">{next?.day_of_week || '—'}</span></div><p className="muted-copy">{next?.ingredients || 'Plan a meal from your pantry.'}</p><div className="macro-row">{(next?.macros || 'Balanced macros').split('  /  ').map((macro) => <span key={macro}>{macro}</span>)}</div><button className="text-button" onClick={() => navigate('menu')}>See full recipe <ArrowRight size={15} /></button></article><article className="content-card soft-outset accent-card"><Sparkles size={22} /><p className="eyebrow">A little guidance</p><h3>Small prep, easier evenings.</h3><p className="muted-copy">{data.tasks.filter((task) => !task.is_completed).length} prep tasks are waiting. A ten-minute head start makes the rest feel lighter.</p><button className="text-button" onClick={() => navigate('tasks')}>View task list <ArrowRight size={15} /></button></article></section>
  </div>;
}
